Blacklist-World:
  - example1
  - world2
VERSION: "1.0-B4"
Number_Format: "#.###"
Boolean:
  true: "On"
  false: "Off"
Blocks:
  COAL_ORE:
    Name: "&8Small_Coal" #You also can you color code in the name
    Price: 100
    Convert: COAL
  IRON_ORE:
    Name: "Small_Iron"
    Price: 200
    Convert: IRON_INGOT
  DIAMOND_ORE:
    Name: "Small_Diamond"
    Price: 300
    Convert: DIAMOND
  COAL_BLOCK:
    Name: "Big_Coal"
    Price: 150
  IRON_BLOCK:
    Name: "Big_Iron"
    Price: 250
  DIAMOND_BLOCK:
    Name: "Big_Diamond"
    Price: 350
  WHITE_STAINED_GLASS: #If you use 1.9 - 1.12.2, set it to STAINED_GLASS
    Name: "White_Glass"
    Price: 50
  YELLOW_STAINED_GLASS: #If you use 1.9 - 1.12.2, set it to STAINED_GLASS;4
    Name: "Yellow_Glass"
    Price: 50
  LAPIS_ORE:
    Name: "Lapis_Ore"
    Price: 200
    Convert: LAPIS_LAZULI #If you use 1.9 - 1.12.2, set it to INK_SACK;4
Default_Max_Storage: 10000
Fortune:
  Chance:
    Player: 10 # level fortune * 10, lv 2 => 20%
    System:
      Min: 1
      Max: 100
  Drop:
    Min: 1
    Max: 5
Message:
  TAKE:
    TYPE: CHAT #ACTION_BAR / CHAT / TITLE
    STATUS: true #true or false
    TITLE:
      TITLE: "&cTake %item% x%amount%&c from Storage"
      SUBTITLE: "&a(%storage%/%max%)"
      FADEIN: 30
      FADEOUT: 10
      STAY: 20
  REMOVE:
    TYPE: ACTION_BAR #ACTION_BAR / CHAT / TITLE
    STATUS: true #true or false
    TITLE:
      TITLE: "&c-%amount% %item%"
      SUBTITLE: "&a(%storage%/%max%)"
      FADEIN: 30
      FADEOUT: 10
      STAY: 20
  ADD:
    TYPE: CHAT #ACTION_BAR / CHAT / TITLE
    STATUS: true #true or false
    TITLE:
      TITLE: "&aAdd %item% &7(x%amount%)&a to Storage"
      SUBTITLE: "&a(%storage%/%max%)"
      FADEIN: 30
      FADEOUT: 10
      STAY: 20
  RECEIVE:
    TYPE: ACTION_BAR #ACTION_BAR / CHAT / TITLE
    STATUS: true #true or false
    TITLE:
      TITLE: "&a+%amount% %item%"
      SUBTITLE: "&a(%storage%/%max%)"
      FADEIN: 30
      FADEOUT: 10
      STAY: 20
  SELL:
    TYPE: ACTION_BAR #ACTION_BAR / CHAT / TITLE
    STATUS: true #true or false
    TITLE:
      TITLE: "&eSold %amount% x%item%"
      SUBTITLE: "&a+ %money% &d| &b(%storage%/%max%)"
      FADEIN: 30
      FADEOUT: 10
      STAY: 20
  FULL:
    TYPE: TITLE #ACTION_BAR / CHAT / TITLE
    TITLE:
      TITLE: "&cWarning"
      SUBTITLE: "&c%item%&6 storage has reached its limit"
      FADEIN: 30
      FADEOUT: 10
      STAY: 20
  TOGGLE:
    TYPE: CHAT #ACTION_BAR / CHAT
    STATUS: true #true or false