name: Storage
version: '${project.version} ${devbuild.number}'
main: net.danh.storage.Storage
api-version: 1.13
authors: [ VoChiDanh ]
softdepend:
  - Vault
  - PlaceholderAPI
commands:
  Storage:
    aliases:
      - store
      - kho
    description: Storage Commands
  APick:
    aliases: [autopickup]
    description: Toggle Pickup
  ASmelt:
    aliases: [autosmelt]
    description: Toggle Smelt
