name: Storage
version: '${project.parent.version}'
main: net.danh.storage.Storage
authors: [ VoChiDanh ]
api-version: 1.13
softdepend:
  - Vault
  - PlaceholderAPI
  - WorldGuard
commands:
  Storage:
    aliases:
      - store
      - kho
    description: Storage Commands
  APick:
    aliases: [ autopickup ]
    description: Toggle Pickup
  ASmelt:
    aliases: [ autosmelt ]
    description: Toggle Smelt
