name: Development Builds
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package
      - uses: "actions/upload-artifact@v3"
        with:
          name: "[DevBuild]-Storage"
          path: |
            ./Storage-Legacy/target/Storage-Legacy.jar
            ./Storage-1_13/target/Storage-1_13.jar
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{github.repository}}
          separator: "/"
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+07:00"
      - name: Discord Webhook Action 1
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL_TEST }}
          username: "${{ steps.split.outputs._1 }}"
          embed-title: "Development Builds"
          avatar-url: "https://github.com/${{ steps.split.outputs._0 }}.png"
          embed-footer-text: "${{ steps.split.outputs._1 }} Build #${{ steps.current-time.outputs.month }}${{ steps.current-time.outputs.day }}${{ steps.current-time.outputs.hour }}${{ steps.current-time.outputs.minute }}"
          embed-color: "65280"
          embed-description: |
            ${{ github.event.head_commit.message }}
                        
            Developer: [`${{ github.actor }}`](https://github.com/${{ github.actor }})
            Download: [`${{ github.run_id }}`](https://api.github.com/${{github.repository}}/actions/artifacts/${{ github.artifact_id }}/zip)

